// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, exports, fs;

  Promise = require('bluebird');

  fs = Promise.promisifyAll(require('fs'));

  module.exports = exports = function(ledFile) {
    var blink, ledOff, ledOn;
    ledOn = function() {
      return fs.writeFileAsync(ledFile, 1);
    };
    ledOff = function() {
      return fs.writeFileAsync(ledFile, 0);
    };
    blink = function(ms) {
      if (ms == null) {
        ms = 200;
      }
      return ledOn().delay(ms).then(ledOff);
    };
    blink.pattern = (function() {
      var blinking, start;
      blinking = null;
      start = function(pattern) {
        var _i, _ref, _results;
        return Promise.resolve((function() {
          _results = [];
          for (var _i = 0, _ref = pattern.blinks; 0 <= _ref ? _i < _ref : _i > _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
          return _results;
        }).apply(this)).cancellable().each(function() {
          return blink(pattern.onDuration).delay(pattern.offDuration);
        }).delay(pattern.pause).then(function() {
          return start(pattern);
        });
      };
      return {
        start: function(pattern) {
          var fullPattern, _ref, _ref1, _ref2, _ref3;
          if (pattern == null) {
            pattern = {};
          }
          if (blinking != null) {
            return false;
          }
          fullPattern = {
            blinks: (_ref = pattern.blinks) != null ? _ref : 1,
            onDuration: (_ref1 = pattern.onDuration) != null ? _ref1 : 200,
            offDuration: (_ref2 = pattern.offDuration) != null ? _ref2 : 200,
            pause: (_ref3 = pattern.pause) != null ? _ref3 : 0
          };
          blinking = start(fullPattern);
        },
        stop: function() {
          if (blinking == null) {
            return false;
          }
          blinking.cancel()["catch"](Promise.CancellationError, function() {});
          ledOff();
          return blinking = null;
        }
      };
    })();
    return blink;
  };

}).call(this);
